version: "3.8"

services:
  # POSTGRESQL
  db:
    image: postgres:9.5
    container_name: drf_postgresql

    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - ./db:/var/lib/postgresql/data
    secrets:
      - POSTG_PASSWORD

    environment:
      POSTGRES_DB: DRF
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/POSTG_PASSWORD
      PGDATA: ./db

    deploy:
      replicas: 1
      placement:
        constraints: [ node.labels.db==db ]

  # Django
  api:
    image: drf_test:0.0.1
    container_name: drf_test

    depends_on:
      - db
      - redis
    volumes:
      - .:/drf
      - /etc/localtime:/etc/localtime:ro

    deploy:
      replicas: 1
      placement:
        constraints: [ node.labels.db==db ]

  # Redis
  redis:
    containser_name: redis
    image: redis:lastest

    ports:
      - 6379:6379
    volumes:
      - redis:/data

    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [ node.labels.redis==redis ]

  # Nginx
  nginx:
    image: nginx:1.19.5
    container_name: nginx

    networks:
      - network
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    secrets:
      - fullchain
      - privkey
    ports:
      - 433:433

  # Celery
  worker:
    image: celery:4.0
    container_name: celery_worker
